import jsPDF from "jspdf";
import { childProfile, doctorBrief, weightSeries, adultReportChiara, geriatricReportRiccardo } from "./mockData";
import { tr } from "./i18nRuntime";

export type ReportLang = "it" | "en";

/** Translation table for the static labels rendered in PDFs.
 *  Clinical free-text (mock data) stays as-is — only chrome/labels translate. */
const PDF_STR: Record<string, { it: string; en: string }> = {
  briefingPediatra: { it: "BRIEFING PEDIATRA  ·  1 PAGINA", en: "PEDIATRIC BRIEFING  ·  1 PAGE" },
  briefingMmg: { it: "BRIEFING MEDICO DI BASE  ·  1 PAGINA", en: "GP BRIEFING  ·  1 PAGE" },
  briefingGeriatra: { it: "BRIEFING GERIATRA  ·  1 PAGINA", en: "GERIATRIC BRIEFING  ·  1 PAGE" },
  reportOf: { it: "Report di", en: "Report for" },
  forPed: { it: "Per", en: "For" },
  forMmg: { it: "Per il MMG", en: "For the GP" },
  forGer: { it: "Per il geriatra / cardiologo", en: "For the geriatrician / cardiologist" },
  ageChrono: { it: "ETÀ CRONOLOGICA", en: "CHRONOLOGICAL AGE" },
  ageCorrected: { it: "ETÀ CORRETTA", en: "CORRECTED AGE" },
  age: { it: "ETÀ", en: "AGE" },
  bmi: { it: "BMI", en: "BMI" },
  birth: { it: "NASCITA", en: "BIRTH" },
  vaccines: { it: "VACCINI", en: "VACCINES" },
  done: { it: "Fatti", en: "Done" },
  next: { it: "Prossimo", en: "Next" },
  er: { it: "PS / RICOVERI", en: "ER / ADMISSIONS" },
  daycare: { it: "NIDO", en: "DAYCARE" },
  growthWeight: { it: "CRESCITA — PESO", en: "GROWTH — WEIGHT" },
  weeks: { it: "Settimane (età post-mestruale)", en: "Weeks (post-menstrual age)" },
  band: { it: "Corridoio 10-90", en: "10-90 corridor" },
  birthShort: { it: "Nasc.", en: "Birth" },
  dischShort: { it: "Dim.", en: "Disch." },
  todayShort: { it: "Oggi", en: "Today" },
  feeding: { it: "ALIMENTAZIONE", en: "FEEDING" },
  therapy: { it: "TERAPIA IN CORSO", en: "ONGOING THERAPY" },
  refMlKg: { it: "rif. 150-180", en: "ref. 150-180" },
  refKcal: { it: "rif. 110-130", en: "ref. 110-130" },
  refProt: { it: "rif. 2.5-4", en: "ref. 2.5-4" },
  openIssues: { it: "PROBLEMI APERTI DALLA DIMISSIONE", en: "OPEN ISSUES SINCE DISCHARGE" },
  currentProblems: { it: "PROBLEMI ATTUALI", en: "CURRENT PROBLEMS" },
  palmTip: { it: "TIP DI PALM", en: "PALM TIP" },
  history: { it: "ANAMNESI RILEVANTE", en: "RELEVANT HISTORY" },
  reminders: { it: "REMINDER PER IL MEDICO", en: "REMINDERS FOR THE DOCTOR" },
  context: { it: "CONTESTO CLINICO", en: "CLINICAL CONTEXT" },
  bp: { it: "PRESSIONE", en: "BLOOD PRESSURE" },
  bp7: { it: "PRESSIONE 7GG", en: "BP (7-DAY AVG)" },
  hr: { it: "FREQUENZA", en: "HEART RATE" },
  temp: { it: "TEMPERATURA", en: "TEMPERATURE" },
  tempShort: { it: "TEMP", en: "TEMP" },
  satO2: { it: "SAT O2", en: "O2 SAT" },
  labs: { it: "ESAMI RECENTI", en: "RECENT LABS" },
  meds: { it: "TERAPIA IN CORSO", en: "ONGOING THERAPY" },
  reasons: { it: "MOTIVI DELLA VISITA", en: "REASONS FOR VISIT" },
  lifestyle: { it: "STILE DI VITA · ULTIMI 7 GG", en: "LIFESTYLE · LAST 7 DAYS" },
  lifestyleShort: { it: "STILE DI VITA · 7 GG", en: "LIFESTYLE · 7 DAYS" },
  conditions: { it: "PATOLOGIE ATTIVE", en: "ACTIVE CONDITIONS" },
  polyAdh: { it: "POLITERAPIA · ADERENZA", en: "POLYTHERAPY · ADHERENCE" },
  alerts: { it: "ALERT DALLA APP DEL CAREGIVER", en: "ALERTS FROM CAREGIVER APP" },
  ref: { it: "rif.", en: "ref." },
  footer: {
    it: "Generato da Palm · supporto educativo, non sostituisce diagnosi o terapia medica",
    en: "Generated by Palm · educational support, not a substitute for diagnosis or medical therapy",
  },
};
const TR = (k: keyof typeof PDF_STR, lang: ReportLang) => PDF_STR[k][lang];

/**
 * One-page A4 doctor briefing — Palm brand aligned.
 * Pastel palette, generous whitespace, refined typography (helvetica as
 * jsPDF doesn't ship Fraunces; we lean on weight + size for hierarchy).
 */

// ─── Brand palette (RGB) ─────────────────────────────────────────────────
const C = {
  ink: { r: 42, g: 38, b: 56 },          // deep plum-ink
  body: { r: 70, g: 64, b: 84 },
  muted: { r: 130, g: 124, b: 142 },
  hairline: { r: 232, g: 226, b: 236 },
  // Pastels
  peach: { r: 244, g: 178, b: 168 },
  peachSoft: { r: 253, g: 234, b: 228 },
  lavender: { r: 196, g: 184, b: 226 },
  lavenderSoft: { r: 240, g: 234, b: 250 },
  mint: { r: 178, g: 220, b: 198 },
  mintSoft: { r: 232, g: 245, b: 238 },
  sky: { r: 188, g: 216, b: 236 },
  skySoft: { r: 234, g: 244, b: 250 },
  amber: { r: 240, g: 198, b: 138 },
  paper: { r: 252, g: 250, b: 252 },
  card: { r: 255, g: 255, b: 255 },
};

export function generateDoctorPdf(lang: ReportLang = "it") {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const PW = doc.internal.pageSize.getWidth();   // 595
  const PH = doc.internal.pageSize.getHeight();  // 842
  const M = 28;                                  // tight margin to fit one page
  const W = PW - M * 2;

  // Soft paper background
  setFill(C.paper);
  doc.rect(0, 0, PW, PH, "F");

  // Wrap doc.text and doc.splitTextToSize so every string is sanitized to
  // Latin-1-safe equivalents. jsPDF core fonts (helvetica) cannot render
  // arrows, subscripts, em-dashes etc.
  // When the active language is English, every drawn string is also routed
  // through the runtime IT→EN translator (static dict + AI cache) so all
  // clinical free-text from mockData lands in the PDF in English.
  const trIfEn = (s: string) => (lang === "en" ? tr(s, "en") : s);
  const _origText = doc.text.bind(doc);
  doc.text = ((text: string | string[], x: number, yy: number, opts?: unknown) => {
    const translated = Array.isArray(text) ? text.map(trIfEn) : trIfEn(text as string);
    const cleaned = Array.isArray(translated) ? translated.map(cleanText) : cleanText(translated as string);
    return _origText(cleaned as string | string[], x, yy, opts as never);
  }) as typeof doc.text;
  const _origSplit = doc.splitTextToSize.bind(doc);
  doc.splitTextToSize = ((text: string, maxLen: number, opts?: unknown) =>
    _origSplit(cleanText(trIfEn(text)), maxLen, opts as never)) as typeof doc.splitTextToSize;

  // ═══ HEADER ═══════════════════════════════════════════════════════════
  const headerH = 64;
  // Gradient-ish header: peach band with lavender accent stripe
  setFill(C.peachSoft);
  doc.roundedRect(M, M, W, headerH, 14, 14, "F");
  setFill(C.peach);
  doc.roundedRect(M, M, 5, headerH, 2.5, 2.5, "F");

  // Palm wordmark — single line, no overlap
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  setText(C.ink);
  doc.text("Palm", M + 18, M + 24);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  setText(C.muted);
  doc.text(TR("briefingPediatra", lang), M + 56, M + 24);

  // Patient name + meta
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  setText(C.ink);
  doc.text(`${TR("reportOf", lang)} ${childProfile.name}`, M + 18, M + 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  setText(C.body);
  doc.text(
    `${TR("forPed", lang)} ${childProfile.pediatrician}   ${formatDate(new Date())}`,
    M + 18,
    M + 56
  );

  // Age pills (right side)
  const pillY = M + 18;
  drawAgePill(PW - M - 178, pillY, 84, TR("ageChrono", lang), doctorBrief.ageChronological, C.lavender, C.lavenderSoft);
  drawAgePill(PW - M - 90, pillY, 84, TR("ageCorrected", lang), "18 gg", C.mint, C.mintSoft);

  let y = M + headerH + 12;

  // ═══ ROW 1: Birth + Vaccines + ER + Daycare (compact strip) ═══════════
  const stripH = 56;
  const colW = (W - 18) / 4;
  drawInfoCard(M + 0,          y, colW, stripH, TR("birth", lang),    `${doctorBrief.birth.term}\n${doctorBrief.birth.mode}\nAPGAR ${doctorBrief.birth.apgar} · TIN ${doctorBrief.birth.ninuStay}`, C.peach);
  drawInfoCard(M + colW + 6,   y, colW, stripH, TR("vaccines", lang), `${TR("done", lang)}: ${doctorBrief.vaccines.done[0]}\n${TR("next", lang)}: ${doctorBrief.vaccines.next}`, C.sky);
  drawInfoCard(M + (colW+6)*2, y, colW, stripH, TR("er", lang),       doctorBrief.erVisits.map(e => `${e.date}\n${e.reason}`).join("\n"), C.amber);
  drawInfoCard(M + (colW+6)*3, y, colW, stripH, TR("daycare", lang),  doctorBrief.daycare.note, C.lavender);
  y += stripH + 12;

  // ═══ ROW 2: Growth chart (left) + Feeding & Therapy (right) ═══════════
  const row2H = 168;
  const chartW = W * 0.58 - 4;
  const sideW = W * 0.42 - 4;

  drawGrowthChart(M, y, chartW, row2H);
  drawFeedingTherapy(M + chartW + 8, y, sideW, row2H);
  y += row2H + 12;

  // ═══ ROW 3: Open issues (left) + Current problems (right) ═════════════
  const row3H = 156;
  const halfW = (W - 8) / 2;
  drawOpenIssues(M, y, halfW, row3H);
  drawCurrentProblems(M + halfW + 8, y, halfW, row3H);
  y += row3H + 12;

  // ═══ ROW 4: History + Reminders ═══════════════════════════════════════
  const row4H = 92;
  drawHistory(M, y, halfW, row4H);
  drawReminders(M + halfW + 8, y, halfW, row4H);
  y += row4H + 10;

  // ═══ FOOTER ═══════════════════════════════════════════════════════════
  setDraw(C.hairline);
  doc.setLineWidth(0.5);
  doc.line(M, PH - 28, PW - M, PH - 28);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  setText(C.muted);
  doc.text(TR("footer", lang), M, PH - 16);
  doc.text(`palm.health · ${formatDate(new Date())}`, PW - M, PH - 16, { align: "right" });

  doc.save(`Palm_Report_${childProfile.name}_${new Date().toISOString().slice(0, 10)}.pdf`);

  // ═══════════════════════════════════════════════════════════════════════
  // Helpers
  // ═══════════════════════════════════════════════════════════════════════

  function setText(c: { r: number; g: number; b: number }) { doc.setTextColor(c.r, c.g, c.b); }
  function setFill(c: { r: number; g: number; b: number }) { doc.setFillColor(c.r, c.g, c.b); }
  function setDraw(c: { r: number; g: number; b: number }) { doc.setDrawColor(c.r, c.g, c.b); }

  // jsPDF core fonts (helvetica) only support Latin-1. Replace anything outside
  // (subscripts, arrows, em/en-dashes, smart quotes) with safe equivalents so
  // we never get garbled glyphs in the PDF.
  function cleanText(s: string): string {
    return s
      .replace(/[₀₁₂₃₄₅₆₇₈₉]/g, (c) => "0123456789"["₀₁₂₃₄₅₆₇₈₉".indexOf(c)])
      .replace(/[⁰¹²³⁴⁵⁶⁷⁸⁹]/g, (c) => "0123456789"["⁰¹²³⁴⁵⁶⁷⁸⁹".indexOf(c)])
      .replace(/→/g, "»")
      .replace(/←/g, "«")
      .replace(/[—–]/g, "-")
      .replace(/[“”„]/g, '"')
      .replace(/[‘’‚]/g, "'")
      .replace(/…/g, "...");
  }

  function formatDate(d: Date) {
    return d.toLocaleDateString(lang === "en" ? "en-US" : "it-IT", { day: "numeric", month: "long", year: "numeric" });
  }

  function drawAgePill(x: number, yy: number, w: number, label: string, value: string, accent: typeof C.peach, soft: typeof C.peachSoft) {
    setFill(soft);
    doc.roundedRect(x, yy, w, 36, 8, 8, "F");
    setFill(accent);
    doc.circle(x + 8, yy + 18, 2.4, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    setText(C.muted);
    doc.text(label, x + 14, yy + 13);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    setText(C.ink);
    doc.text(value, x + 14, yy + 26);
  }

  function drawInfoCard(x: number, yy: number, w: number, h: number, label: string, body: string, accent: typeof C.peach) {
    // Card
    setFill(C.card);
    doc.roundedRect(x, yy, w, h, 8, 8, "F");
    setDraw(C.hairline);
    doc.setLineWidth(0.5);
    doc.roundedRect(x, yy, w, h, 8, 8, "S");
    // Accent dot + label
    setFill(accent);
    doc.circle(x + 9, yy + 11, 2.2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    setText(C.muted);
    doc.text(label, x + 15, yy + 13);
    // Body
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.8);
    setText(C.body);
    const lines = doc.splitTextToSize(body, w - 16);
    doc.text(lines, x + 8, yy + 24);
  }

  function drawGrowthChart(x: number, yy: number, w: number, h: number) {
    // Card frame
    setFill(C.card);
    doc.roundedRect(x, yy, w, h, 10, 10, "F");
    setDraw(C.hairline);
    doc.setLineWidth(0.5);
    doc.roundedRect(x, yy, w, h, 10, 10, "S");

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setText(C.muted);
    doc.text(TR("growthWeight", lang), x + 12, yy + 14);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    setText(C.ink);
    doc.text(`${doctorBrief.weight.current.value} g`, x + 12, yy + 28);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    setText(C.body);
    doc.text(
      lang === "en"
        ? `${doctorBrief.weight.current.percentile}th percentile · INeS preterm curve`
        : `${doctorBrief.weight.current.percentile}° percentile · curva INeS pretermine`,
      x + 60,
      yy + 28,
    );

    // Chart inner area (Fenton-style: percentile corridors)
    const padL = 28;
    const padR = 12;
    const padT = 38;
    const padB = 22;
    const cx0 = x + padL;
    const cy0 = yy + padT;
    const cw = w - padL - padR;
    const ch = h - padT - padB;

    // Y axis range in grams
    const yMin = 1200;
    const yMax = 4000;
    const yToPx = (g: number) => cy0 + ch - ((g - yMin) / (yMax - yMin)) * ch;

    // X axis: weeks 30 → 44 (gestational/post-natal age in weeks)
    const xMin = 30;
    const xMax = 44;
    const xToPx = (wk: number) => cx0 + ((wk - xMin) / (xMax - xMin)) * cw;

    // Synthetic Fenton-like growth bands (smooth curves) — illustrative
    // For each percentile we generate y(g) at each week
    const percentiles = [
      { p: 97, color: C.hairline, dash: true },
      { p: 90, color: C.lavender, dash: true },
      { p: 50, color: C.peach,    dash: false },
      { p: 10, color: C.lavender, dash: true },
      { p: 3,  color: C.hairline, dash: true },
    ];

    // Reference values per percentile (approx Fenton boys, grams) at weeks 30,32,34,36,38,40,42,44
    const refGrid: Record<number, number[]> = {
      97: [1700, 2100, 2600, 3050, 3500, 3900, 4250, 4500],
      90: [1550, 1950, 2400, 2850, 3250, 3600, 3950, 4200],
      50: [1300, 1700, 2100, 2550, 2950, 3300, 3650, 3900],
      10: [1100, 1450, 1800, 2200, 2600, 2950, 3250, 3500],
      3:  [1000, 1300, 1650, 2050, 2400, 2750, 3050, 3300],
    };
    const refWeeks = [30, 32, 34, 36, 38, 40, 42, 44];

    // Healthy band shading (10–90)
    setFill(C.mintSoft);
    const bandPath = (top: number[], bot: number[]) => {
      const pts: { x: number; y: number }[] = [];
      refWeeks.forEach((wk, i) => pts.push({ x: xToPx(wk), y: yToPx(top[i]) }));
      for (let i = refWeeks.length - 1; i >= 0; i--) {
        pts.push({ x: xToPx(refWeeks[i]), y: yToPx(bot[i]) });
      }
      // Approximate filled polygon via triangles
      doc.setLineWidth(0);
      // jsPDF lacks polygon fill, fake it with a series of trapezoids
      for (let i = 0; i < refWeeks.length - 1; i++) {
        const x1 = xToPx(refWeeks[i]);
        const x2 = xToPx(refWeeks[i + 1]);
        const yt1 = yToPx(top[i]);
        const yt2 = yToPx(top[i + 1]);
        const yb1 = yToPx(bot[i]);
        const yb2 = yToPx(bot[i + 1]);
        // two triangles per segment
        doc.triangle(x1, yt1, x2, yt2, x2, yb2, "F");
        doc.triangle(x1, yt1, x2, yb2, x1, yb1, "F");
      }
      void pts;
    };
    bandPath(refGrid[90], refGrid[10]);

    // Y grid + labels
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6);
    setText(C.muted);
    setDraw(C.hairline);
    doc.setLineWidth(0.3);
    const yTicks = [1500, 2000, 2500, 3000, 3500, 4000];
    yTicks.forEach((g) => {
      const py = yToPx(g);
      doc.line(cx0, py, cx0 + cw, py);
      doc.text(`${g / 1000}kg`, cx0 - 3, py + 2, { align: "right" });
    });

    // X labels (weeks)
    const xTicks = [30, 32, 34, 36, 38, 40, 42, 44];
    xTicks.forEach((wk) => {
      const px = xToPx(wk);
      doc.text(`${wk}`, px, cy0 + ch + 10, { align: "center" });
    });
    doc.setFontSize(6);
    setText(C.muted);
    doc.text(TR("weeks", lang), cx0 + cw / 2, cy0 + ch + 18, { align: "center" });

    // Draw percentile lines (smooth-ish polylines)
    percentiles.forEach(({ p, color, dash }) => {
      setDraw(color);
      doc.setLineWidth(p === 50 ? 0.9 : 0.5);
      if (dash) doc.setLineDashPattern([1.5, 1.5], 0);
      else doc.setLineDashPattern([], 0);
      const ys = refGrid[p];
      for (let i = 0; i < refWeeks.length - 1; i++) {
        doc.line(xToPx(refWeeks[i]), yToPx(ys[i]), xToPx(refWeeks[i + 1]), yToPx(ys[i + 1]));
      }
      // Label at right
      doc.setFontSize(5.5);
      setText(C.muted);
      doc.text(lang === "en" ? `${p}th` : `${p}°`, xToPx(44) + 1, yToPx(ys[ys.length - 1]) + 2);
    });
    doc.setLineDashPattern([], 0);

    // Patient trajectory: birth (31+2), discharge (~38wk), current (~40+2)
    const patientPts = [
      { wk: 31.3, g: doctorBrief.weight.birth.value, label: TR("birthShort", lang) },
      { wk: 38, g: doctorBrief.weight.discharge.value, label: TR("dischShort", lang) },
      { wk: 40.3, g: doctorBrief.weight.current.value, label: TR("todayShort", lang) },
    ];
    setDraw(C.peach);
    doc.setLineWidth(1.6);
    for (let i = 0; i < patientPts.length - 1; i++) {
      doc.line(xToPx(patientPts[i].wk), yToPx(patientPts[i].g), xToPx(patientPts[i + 1].wk), yToPx(patientPts[i + 1].g));
    }
    patientPts.forEach((pt) => {
      // halo
      setFill(C.peachSoft);
      doc.circle(xToPx(pt.wk), yToPx(pt.g), 4, "F");
      setFill(C.peach);
      doc.circle(xToPx(pt.wk), yToPx(pt.g), 2.4, "F");
      // label
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6);
      setText(C.ink);
      doc.text(pt.label, xToPx(pt.wk), yToPx(pt.g) - 6, { align: "center" });
      doc.setFont("helvetica", "normal");
      setText(C.muted);
      doc.text(`${pt.g}g`, xToPx(pt.wk), yToPx(pt.g) + 11, { align: "center" });
    });

    // Mini legend (top-right of card, away from axes)
    const lgX = x + w - 130;
    const lgY = yy + 14;
    setFill(C.mintSoft); doc.rect(lgX, lgY - 4, 6, 4, "F");
    setText(C.muted); doc.setFont("helvetica", "normal"); doc.setFontSize(6);
    doc.text(TR("band", lang), lgX + 9, lgY);
    setFill(C.peach); doc.circle(lgX + 56, lgY - 2, 1.8, "F");
    doc.text(childProfile.name, lgX + 60, lgY);
  }

  function drawFeedingTherapy(x: number, yy: number, w: number, h: number) {
    setFill(C.card);
    doc.roundedRect(x, yy, w, h, 10, 10, "F");
    setDraw(C.hairline);
    doc.setLineWidth(0.5);
    doc.roundedRect(x, yy, w, h, 10, 10, "S");

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setText(C.muted);
    doc.text(TR("feeding", lang), x + 12, yy + 14);

    const f = doctorBrief.feeding;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    setText(C.body);
    const typeLines = doc.splitTextToSize(f.type, w - 24);
    doc.text(typeLines, x + 12, yy + 26);

    // Three mini stats
    const statY = yy + 26 + typeLines.length * 9 + 6;
    const statW = (w - 24 - 12) / 3;
    const stats = [
      { label: lang === "en" ? "ml/kg/day" : "ml/kg/die", value: `${f.mlPerKgDie}`, ref: TR("refMlKg", lang) },
      { label: lang === "en" ? "kcal/kg/day" : "kcal/kg/die", value: `${f.kcalPerKgDie}`, ref: TR("refKcal", lang) },
      { label: lang === "en" ? "g prot/kg/day" : "g prot/kg/die", value: `${f.proteinGPerKgDie}`, ref: TR("refProt", lang) },
    ];
    stats.forEach((s, i) => {
      const sx = x + 12 + (statW + 6) * i;
      setFill(C.peachSoft);
      doc.roundedRect(sx, statY, statW, 36, 6, 6, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      setText(C.ink);
      doc.text(s.value, sx + statW / 2, statY + 14, { align: "center" });
      doc.setFont("helvetica", "normal");
      doc.setFontSize(6);
      setText(C.muted);
      doc.text(s.label, sx + statW / 2, statY + 24, { align: "center" });
      doc.setFont("helvetica", "bold");
      doc.setFontSize(5.5);
      setText(C.muted);
      doc.text(s.ref, sx + statW / 2, statY + 31, { align: "center" });
    });

    // Therapy
    const thY = statY + 44;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setText(C.muted);
    doc.text(TR("therapy", lang), x + 12, thY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    setText(C.body);
    doctorBrief.ongoingTherapy.forEach((t, i) => {
      setFill(C.lavender);
      doc.circle(x + 14, thY + 10 + i * 11 - 2, 1.3, "F");
      doc.text(t, x + 19, thY + 10 + i * 11);
    });
  }

  function drawOpenIssues(x: number, yy: number, w: number, h: number) {
    setFill(C.card);
    doc.roundedRect(x, yy, w, h, 10, 10, "F");
    setDraw(C.hairline);
    doc.setLineWidth(0.5);
    doc.roundedRect(x, yy, w, h, 10, 10, "S");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setText(C.muted);
    doc.text(TR("openIssues", lang), x + 12, yy + 14);

    let py = yy + 24;
    doctorBrief.openIssuesSinceDischarge.forEach((it) => {
      setFill(C.amber);
      doc.circle(x + 14, py + 4, 2, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      setText(C.ink);
      doc.text(it.issue, x + 20, py + 6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.2);
      setText(C.body);
      const planLines = doc.splitTextToSize(`» ${it.plan}`, w - 28);
      doc.text(planLines, x + 20, py + 16);
      py += 16 + planLines.length * 8 + 4;
    });
  }

  function drawCurrentProblems(x: number, yy: number, w: number, h: number) {
    setFill(C.card);
    doc.roundedRect(x, yy, w, h, 10, 10, "F");
    setDraw(C.hairline);
    doc.setLineWidth(0.5);
    doc.roundedRect(x, yy, w, h, 10, 10, "S");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setText(C.muted);
    doc.text(TR("currentProblems", lang), x + 12, yy + 14);

    let py = yy + 22;
    doctorBrief.currentProblems.forEach((p) => {
      const probLines = doc.splitTextToSize(p.problem, w - 28);
      const detLines = doc.splitTextToSize(p.detail, w - 28);
      const tipLines = doc.splitTextToSize(p.palmTip, w - 28);
      const blockH = 4 + probLines.length * 9 + detLines.length * 8 + 4 + 8 + tipLines.length * 8 + 6;

      // Left mint stripe (matches block height)
      setFill(C.mint);
      doc.rect(x + 10, py, 2.5, blockH - 6, "F");

      // Problem title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.8);
      setText(C.ink);
      doc.text(probLines, x + 17, py + 6);

      // Detail
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      setText(C.body);
      doc.text(detLines, x + 17, py + 6 + probLines.length * 9);

      // Tip — own line, no overlap
      const tipLabelY = py + 6 + probLines.length * 9 + detLines.length * 8 + 6;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.5);
      setText(C.peach);
      doc.text(TR("palmTip", lang), x + 17, tipLabelY);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      setText(C.body);
      doc.text(tipLines, x + 17, tipLabelY + 8);

      py += blockH;
    });
  }

  function drawHistory(x: number, yy: number, w: number, h: number) {
    setFill(C.lavenderSoft);
    doc.roundedRect(x, yy, w, h, 10, 10, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setText(C.muted);
    doc.text(TR("history", lang), x + 12, yy + 14);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.3);
    setText(C.body);
    doctorBrief.relevantHistory.forEach((t, i) => {
      setFill(C.lavender);
      doc.circle(x + 14, yy + 26 + i * 11, 1.4, "F");
      const lines = doc.splitTextToSize(t, w - 28);
      doc.text(lines, x + 20, yy + 28 + i * 11);
    });
  }

  function drawReminders(x: number, yy: number, w: number, h: number) {
    setFill(C.peachSoft);
    doc.roundedRect(x, yy, w, h, 10, 10, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setText(C.peach);
    doc.text(TR("reminders", lang), x + 12, yy + 14);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.3);
    setText(C.ink);
    doctorBrief.doctorReminders.forEach((r, i) => {
      setFill(C.peach);
      doc.circle(x + 14, yy + 26 + i * 11, 1.4, "F");
      const lines = doc.splitTextToSize(r, w - 28);
      doc.text(lines, x + 20, yy + 28 + i * 11);
    });
  }

  void weightSeries; // kept for future fine-grained recent trend overlay
}

// ═══════════════════════════════════════════════════════════════════════
// Adult report (Chiara) — for the GP / "medico di base"
// ═══════════════════════════════════════════════════════════════════════

const A = {
  ink: { r: 42, g: 38, b: 56 },
  body: { r: 70, g: 64, b: 84 },
  muted: { r: 130, g: 124, b: 142 },
  hairline: { r: 232, g: 226, b: 236 },
  peach: { r: 244, g: 178, b: 168 },
  peachSoft: { r: 253, g: 234, b: 228 },
  lavender: { r: 196, g: 184, b: 226 },
  lavenderSoft: { r: 240, g: 234, b: 250 },
  mint: { r: 178, g: 220, b: 198 },
  mintSoft: { r: 232, g: 245, b: 238 },
  amber: { r: 240, g: 198, b: 138 },
  amberSoft: { r: 252, g: 240, b: 214 },
  paper: { r: 252, g: 250, b: 252 },
  card: { r: 255, g: 255, b: 255 },
};

function clean(s: string): string {
  return s
    .replace(/[₀₁₂₃₄₅₆₇₈₉]/g, (c) => "0123456789"["₀₁₂₃₄₅₆₇₈₉".indexOf(c)])
    .replace(/[⁰¹²³⁴⁵⁶⁷⁸⁹]/g, (c) => "0123456789"["⁰¹²³⁴⁵⁶⁷⁸⁹".indexOf(c)])
    .replace(/→/g, "»").replace(/←/g, "«")
    .replace(/[—–]/g, "-").replace(/[“”„]/g, '"').replace(/[‘’‚]/g, "'").replace(/…/g, "...");
}

function formatItDate(d: Date, lang: ReportLang = "it") {
  return d.toLocaleDateString(lang === "en" ? "en-US" : "it-IT", { day: "numeric", month: "long", year: "numeric" });
}

function setupSafePdf(doc: jsPDF, lang: ReportLang = "it") {
  const trIfEn = (s: string) => (lang === "en" ? tr(s, "en") : s);
  const _origText = doc.text.bind(doc);
  doc.text = ((text: string | string[], x: number, yy: number, opts?: unknown) => {
    const translated = Array.isArray(text) ? text.map(trIfEn) : trIfEn(text as string);
    const cleaned = Array.isArray(translated) ? translated.map(clean) : clean(translated as string);
    return _origText(cleaned as string | string[], x, yy, opts as never);
  }) as typeof doc.text;
  const _origSplit = doc.splitTextToSize.bind(doc);
  doc.splitTextToSize = ((text: string, maxLen: number, opts?: unknown) =>
    _origSplit(clean(trIfEn(text)), maxLen, opts as never)) as typeof doc.splitTextToSize;
}

function drawAdultGeriatricFrame(
  doc: jsPDF,
  opts: {
    title: string;
    audience: string;
    patient: { name: string; age: string; sex: string; height: string; weight: string; bmi: string };
    headerAccent: typeof A.peach;
    headerSoft: typeof A.peachSoft;
  },
  lang: ReportLang = "it"
) {
  const PW = doc.internal.pageSize.getWidth();
  const PH = doc.internal.pageSize.getHeight();
  const M = 28;
  const W = PW - M * 2;

  doc.setFillColor(A.paper.r, A.paper.g, A.paper.b);
  doc.rect(0, 0, PW, PH, "F");

  // Header
  const headerH = 64;
  doc.setFillColor(opts.headerSoft.r, opts.headerSoft.g, opts.headerSoft.b);
  doc.roundedRect(M, M, W, headerH, 14, 14, "F");
  doc.setFillColor(opts.headerAccent.r, opts.headerAccent.g, opts.headerAccent.b);
  doc.roundedRect(M, M, 5, headerH, 2.5, 2.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(A.ink.r, A.ink.g, A.ink.b);
  doc.text("Palm", M + 18, M + 24);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(A.muted.r, A.muted.g, A.muted.b);
  doc.text(opts.title, M + 56, M + 24);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(A.ink.r, A.ink.g, A.ink.b);
  doc.text(`${TR("reportOf", lang)} ${opts.patient.name}`, M + 18, M + 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(A.body.r, A.body.g, A.body.b);
  doc.text(`${opts.audience}   ${formatItDate(new Date(), lang)}`, M + 18, M + 56);

  // Patient pills (right)
  const pillY = M + 18;
  drawPill(doc, PW - M - 178, pillY, 84, TR("age", lang), `${opts.patient.age} · ${opts.patient.sex}`, opts.headerAccent, opts.headerSoft);
  drawPill(doc, PW - M - 90, pillY, 84, TR("bmi", lang), `${opts.patient.bmi} (${opts.patient.weight})`, A.mint, A.mintSoft);

  return { M, W, PW, PH, y: M + headerH + 12 };
}

function drawPill(doc: jsPDF, x: number, yy: number, w: number, label: string, value: string, accent: typeof A.peach, soft: typeof A.peachSoft) {
  doc.setFillColor(soft.r, soft.g, soft.b);
  doc.roundedRect(x, yy, w, 36, 8, 8, "F");
  doc.setFillColor(accent.r, accent.g, accent.b);
  doc.circle(x + 8, yy + 18, 2.4, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(A.muted.r, A.muted.g, A.muted.b);
  doc.text(label, x + 14, yy + 13);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(A.ink.r, A.ink.g, A.ink.b);
  doc.text(value, x + 14, yy + 26);
}

function drawCardBox(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, accent: typeof A.peach) {
  doc.setFillColor(A.card.r, A.card.g, A.card.b);
  doc.roundedRect(x, y, w, h, 10, 10, "F");
  doc.setDrawColor(A.hairline.r, A.hairline.g, A.hairline.b);
  doc.setLineWidth(0.5);
  doc.roundedRect(x, y, w, h, 10, 10, "S");
  doc.setFillColor(accent.r, accent.g, accent.b);
  doc.circle(x + 9, y + 12, 2.2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(A.muted.r, A.muted.g, A.muted.b);
  doc.text(label, x + 15, y + 14);
}

function drawSoftBox(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, accentText: typeof A.peach, fill: typeof A.peachSoft) {
  doc.setFillColor(fill.r, fill.g, fill.b);
  doc.roundedRect(x, y, w, h, 10, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(accentText.r, accentText.g, accentText.b);
  doc.text(label, x + 12, y + 14);
}

function bulletList(doc: jsPDF, items: string[], x: number, y: number, w: number, accent: typeof A.peach) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.4);
  doc.setTextColor(A.body.r, A.body.g, A.body.b);
  let cy = y;
  items.forEach((t) => {
    const lines = doc.splitTextToSize(t, w - 16);
    doc.setFillColor(accent.r, accent.g, accent.b);
    doc.circle(x + 4, cy + 3, 1.4, "F");
    doc.text(lines, x + 10, cy + 5);
    cy += lines.length * 8.5 + 2;
  });
  return cy;
}

function footer(doc: jsPDF, lang: ReportLang = "it") {
  const PW = doc.internal.pageSize.getWidth();
  const PH = doc.internal.pageSize.getHeight();
  const M = 28;
  doc.setDrawColor(A.hairline.r, A.hairline.g, A.hairline.b);
  doc.setLineWidth(0.5);
  doc.line(M, PH - 28, PW - M, PH - 28);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(A.muted.r, A.muted.g, A.muted.b);
  doc.text(TR("footer", lang), M, PH - 16);
  doc.text(`palm.health · ${formatItDate(new Date(), lang)}`, PW - M, PH - 16, { align: "right" });
}

export function generateAdultPdf(lang: ReportLang = "it") {
  const r = adultReportChiara;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  setupSafePdf(doc, lang);
  const f = drawAdultGeriatricFrame(doc, {
    title: TR("briefingMmg", lang),
    audience: TR("forMmg", lang),
    patient: r.patient,
    headerAccent: A.peach,
    headerSoft: A.peachSoft,
  }, lang);
  let y = f.y;
  const M = f.M, W = f.W;

  // Row 1: context band
  drawSoftBox(doc, M, y, W, 50, TR("context", lang), A.peach, A.peachSoft);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(A.body.r, A.body.g, A.body.b);
  const ctxLines = doc.splitTextToSize(r.context, W - 24);
  doc.text(ctxLines, M + 12, y + 28);
  y += 50 + 10;

  // Row 2: vitals strip
  const vH = 44;
  const vw = (W - 18) / 3;
  const vitals = [
    { l: TR("bp", lang), v: r.vitals.bp, c: A.peach as typeof A.peach },
    { l: TR("hr", lang), v: r.vitals.hr, c: A.lavender as typeof A.peach },
    { l: TR("temp", lang), v: r.vitals.temp, c: A.mint as typeof A.peach },
  ];
  vitals.forEach((v, i) => {
    const x = M + (vw + 9) * i;
    drawCardBox(doc, x, y, vw, vH, v.l, v.c);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(A.ink.r, A.ink.g, A.ink.b);
    doc.text(v.v, x + 12, y + 34);
  });
  y += vH + 10;

  // Row 3: Labs (left) + Meds (right)
  const colH = 130;
  const halfW = (W - 10) / 2;

  drawCardBox(doc, M, y, halfW, colH, TR("labs", lang), A.lavender);
  let ly = y + 26;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  r.labs.forEach((lab) => {
    const dotColor = lab.tone === "good" ? A.mint : lab.tone === "warn" ? A.amber : A.peach;
    doc.setFillColor(dotColor.r, dotColor.g, dotColor.b);
    doc.circle(M + 12, ly + 4, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.6);
    doc.setTextColor(A.ink.r, A.ink.g, A.ink.b);
    doc.text(lab.label, M + 18, ly + 6);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(A.body.r, A.body.g, A.body.b);
    doc.text(lab.value, M + halfW - 12, ly + 6, { align: "right" });
    doc.setFontSize(6.2);
    doc.setTextColor(A.muted.r, A.muted.g, A.muted.b);
    doc.text(`${TR("ref", lang)} ${lab.ref}`, M + halfW - 12, ly + 13, { align: "right" });
    ly += 18;
  });

  drawCardBox(doc, M + halfW + 10, y, halfW, colH, TR("meds", lang), A.mint);
  bulletList(doc, r.meds, M + halfW + 22, y + 26, halfW - 16, A.mint);
  y += colH + 10;

  // Row 4: Reasons + Doctor ask
  const r4H = 96;
  drawSoftBox(doc, M, y, halfW, r4H, TR("reasons", lang), A.peach, A.peachSoft);
  bulletList(doc, r.reasons, M + 12, y + 26, halfW - 16, A.peach);

  drawSoftBox(doc, M + halfW + 10, y, halfW, r4H, TR("reminders", lang), A.amber, A.amberSoft);
  bulletList(doc, r.doctorAsk, M + halfW + 22, y + 26, halfW - 16, A.amber);
  y += r4H + 10;

  // Row 5: Lifestyle + History (compact)
  const r5H = 90;
  drawCardBox(doc, M, y, halfW, r5H, TR("lifestyle", lang), A.lavender);
  bulletList(doc, r.lifestyle, M + 12, y + 26, halfW - 16, A.lavender);

  drawCardBox(doc, M + halfW + 10, y, halfW, r5H, TR("history", lang), A.peach);
  bulletList(doc, r.history, M + halfW + 22, y + 26, halfW - 16, A.peach);

  footer(doc, lang);
  doc.save(`Palm_Report_${r.patient.name.replace(/\s/g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function generateGeriatricPdf(lang: ReportLang = "it") {
  const r = geriatricReportRiccardo;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  setupSafePdf(doc, lang);
  const f = drawAdultGeriatricFrame(doc, {
    title: TR("briefingGeriatra", lang),
    audience: TR("forGer", lang),
    patient: r.patient,
    headerAccent: A.lavender,
    headerSoft: A.lavenderSoft,
  }, lang);
  let y = f.y;
  const M = f.M, W = f.W;

  // Context
  drawSoftBox(doc, M, y, W, 50, TR("context", lang), A.lavender, A.lavenderSoft);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(A.body.r, A.body.g, A.body.b);
  doc.text(doc.splitTextToSize(r.context, W - 24), M + 12, y + 28);
  y += 50 + 10;

  // Vitals (4 columns)
  const vH = 44;
  const vw = (W - 27) / 4;
  const vitals = [
    { l: TR("bp7", lang), v: r.vitals.bp, c: A.peach as typeof A.peach },
    { l: TR("hr", lang), v: r.vitals.hr, c: A.lavender as typeof A.peach },
    { l: TR("tempShort", lang), v: r.vitals.temp, c: A.mint as typeof A.peach },
    { l: TR("satO2", lang), v: r.vitals.sat ?? "—", c: A.amber as typeof A.peach },
  ];
  vitals.forEach((v, i) => {
    const x = M + (vw + 9) * i;
    drawCardBox(doc, x, y, vw, vH, v.l, v.c);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(A.ink.r, A.ink.g, A.ink.b);
    doc.text(v.v, x + 12, y + 34);
  });
  y += vH + 10;

  // Conditions + Meds (with adherence bars)
  const colH = 130;
  const halfW = (W - 10) / 2;

  drawCardBox(doc, M, y, halfW, colH, TR("conditions", lang), A.peach);
  bulletList(doc, r.conditions, M + 12, y + 26, halfW - 16, A.peach);

  drawCardBox(doc, M + halfW + 10, y, halfW, colH, TR("polyAdh", lang), A.mint);
  let my = y + 26;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  r.meds.forEach((m) => {
    const adh = r.adherence.find((a) => m.name.toLowerCase().includes(a.drug.toLowerCase()));
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.4);
    doc.setTextColor(A.ink.r, A.ink.g, A.ink.b);
    doc.text(m.name, M + halfW + 22, my + 4);
    if (adh) {
      const tone = adh.pct >= 90 ? A.mint : adh.pct >= 80 ? A.amber : A.peach;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.8);
      doc.setTextColor(tone.r, tone.g, tone.b);
      doc.text(`${adh.pct}%`, M + W - 14, my + 4, { align: "right" });
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(A.muted.r, A.muted.g, A.muted.b);
    doc.text(m.dose, M + halfW + 22, my + 11);
    // adherence bar
    if (adh) {
      const barX = M + halfW + 22;
      const barW = halfW - 36;
      doc.setFillColor(A.hairline.r, A.hairline.g, A.hairline.b);
      doc.roundedRect(barX, my + 14, barW, 2, 1, 1, "F");
      const tone = adh.pct >= 90 ? A.mint : adh.pct >= 80 ? A.amber : A.peach;
      doc.setFillColor(tone.r, tone.g, tone.b);
      doc.roundedRect(barX, my + 14, (barW * adh.pct) / 100, 2, 1, 1, "F");
    }
    my += 22;
  });
  y += colH + 10;

  // Labs strip + Alerts
  const r3H = 88;
  drawCardBox(doc, M, y, halfW, r3H, TR("labs", lang), A.lavender);
  let ly = y + 26;
  r.labs.forEach((lab) => {
    const dotColor = lab.tone === "good" ? A.mint : lab.tone === "warn" ? A.amber : A.peach;
    doc.setFillColor(dotColor.r, dotColor.g, dotColor.b);
    doc.circle(M + 12, ly + 4, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.4);
    doc.setTextColor(A.ink.r, A.ink.g, A.ink.b);
    doc.text(lab.label, M + 18, ly + 6);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(A.body.r, A.body.g, A.body.b);
    doc.text(lab.value, M + halfW - 12, ly + 6, { align: "right" });
    doc.setFontSize(6);
    doc.setTextColor(A.muted.r, A.muted.g, A.muted.b);
    doc.text(`${TR("ref", lang)} ${lab.ref}`, M + halfW - 12, ly + 12, { align: "right" });
    ly += 16;
  });

  drawSoftBox(doc, M + halfW + 10, y, halfW, r3H, TR("alerts", lang), A.peach, A.peachSoft);
  bulletList(doc, r.alerts, M + halfW + 22, y + 26, halfW - 16, A.peach);
  y += r3H + 10;

  // Lifestyle + Doctor ask
  const r4H = 86;
  drawCardBox(doc, M, y, halfW, r4H, TR("lifestyleShort", lang), A.mint);
  bulletList(doc, r.lifestyle, M + 12, y + 26, halfW - 16, A.mint);

  drawSoftBox(doc, M + halfW + 10, y, halfW, r4H, TR("reminders", lang), A.amber, A.amberSoft);
  bulletList(doc, r.doctorAsk, M + halfW + 22, y + 26, halfW - 16, A.amber);
  footer(doc, lang);
  doc.save(`Palm_Report_${r.patient.name.replace(/\s/g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`);
}
